config/routes.rb
Rails.application.routes.draw do
  resources :articles
  resources :cars
  root 'pages#home'
  get   'about', to: 'pages#about'
  get   'signup', to: 'users#new'
  get    'login', to: 'sessions#new'
  post   'login', to: 'sessions#create'
  delete   'logout', to: "sessions#destroy"
  resources :users , except:[:new]
  resources :categories, except: [:destroy]
end

app/models/article.rb
class Article <ApplicationRecord
    has_many :article_categories
    has_many :categories, through: :article_categories
     
    belongs_to :user
    validates :title , presence: true,length: {minimum:10, maximum:100}
    validates  :description ,presence: true, length: {minimum:10, maximum:300}
   end


  
  

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article , only:[:show,:edit,:update,:destroy]
    before_action :require_user ,except:[:index,:show]
    before_action :require_same_user ,only:[:edit,:update,:destroy]
     #provides to the above actions the method set_article
     
    def index
        @articles = Article.paginate(:page => params[:page])
    end

    def new
        @article=Article.new
    end

      def create
        
      
        
        @article=Article.new(article_params)
        
        @article.user=current_user
        if @article.save
        flash[:notice]="wabe wabe"
        redirect_to article_path(@article)
             
         else
            render 'new'
         end
      end
    
    def show
        # making it an instance variable avaailable to the views
       
       
    end
    
    def edit
        
    end

    def update
        
        if @article.update(article_params)
            flash[:notice]="updated successfully"
            redirect_to article_path(@article)
        else
            render 'edit'
        end
    end
    
     def destroy
       
        @article.destroy
    
        redirect_to articles_path, status: :see_other
       end

     private
     def set_article
        @article=Article.find(params[:id])
        
     end

     def article_params
        params.require(:article).permit(:title,:description,category_ids:[])
     end
     def require_same_user
        if current_user != @article.user && !current_user.admin?
            flash[:alert]="can only edit delete own articles" 
            redirect_to @article
        end
        
     end
end

app/views/articles/_article.html.erb
<div class="new_blog  m-3 position-static">
    <%= link_to 'New Blog' ,new_article_path ,class:'btn btn-success'%>
</div>

<div class="container-fluid">
    <% obj.each do |article|%>

        <div class="card text-center shadow-lg bg-body rounded mb-2">
            <div class="card-header fst-italic">
                Featured On rail by <%= link_to article.user.username,user_path(article.user)%>
            </div>
            <div
                class="text-center justify-content-center align-items-center fw-semibold badge rounded-pill bg-dark m-1 ">
                <% if article.categories.any?%>
                    <%= render article.categories%>
                        <%end%>
            </div>
            <div class="card-body">
                <h5 class="card-title">
                    <%= link_to article.title ,article_path(article) ,class:'text-success'%>
                </h5>
                <p class="card-text">
                    <%= truncate(article.description , length: 10)%>
                </p>
                <div class="d-flex  justify-content-center gap-3 mb-3">
                    <%= link_to 'Gview' ,article_path(article) ,class:'btn btn-success'%>
                        <% if logged_in? && (article.user==current_user || current_user.admin?)%>
                            <%= link_to 'Edit' , edit_article_path(article) ,class:'btn btn-primary'%>
                                <div>
                                    <%= button_to'Delete' ,article_path(article),class:'btn btn-danger' , method:
                                        :delete%>
                                </div>
                                <%end%>
                </div>
                <div class="card-footer text-muted">
                    Posted <%= time_ago_in_words(article.created_at)%> and updated at about <%=
                            time_ago_in_words(article.updated_at)%>
                </div>
            </div>
        </div>

        <%end%>

</div>

app/views/articles/_form.html.erb
<%= render 'shared/errors' ,obj: @article %>
<%= form_with(model: @article, data: { turbo: "false" }) do |f| %>
  <div class="mb-3">
    <%= f.label :title ,class:"form-label"%><br />
    <%= f.text_field :title ,class:"form-control",placeholder:"Currently having water ....." %>
  </div>
  <div class="mb-3">
    <%= f.label :description ,class:"form-label"%><br />
    <%= f.text_area :description ,class:"form-control",rows:3%>
  </div>
  <div class="mb-3">
    <%= f.label :category ,class:"form-label"%><br />
    <%= f.collection_select(:category_ids, Category.order(:id), :id, :name, {prompt: "Please Select a Sector"} , {multiple: true,class:'form-select multiple'})%>
  </div>
  <div class="mb-3">
    <%= f.submit(@article.new_record? ? "Create Blog" : "Update_blog" ,class:"btn btn-outline-success")%>
  </p>
</div>
<%end%>

app/views/articles/edit.html.erb
<div class="container">
    <div class="row align-content-center text-center">
        <div class="col-12">
            <h1 class="lead mt-2">Edit article</h1>
            <%= render 'form' %>
                <%= link_to 'back to mama' ,articles_path %>
        </div>
    </div>
</div>

app/views/articles/index.html.erb
<h4 class="text-center mt-4">Blogs</h4>
<%= render 'article' ,obj: @articles %>

app/views/articles/new.html.erb
<div class="container">
    <div class="row align-content-center text-center">
        <div class="col-12">
            <h1 class="lead">Create a new article</h1>
            <%= render 'form' %>
                <%= link_to 'back to mama' ,articles_path %>
        </div>
    </div>
</div>

app/views/articles/show.html.erb
<div class="new_blog m-3">
  <%= link_to 'go to mama' ,root_path ,class:'btn btn-success'%>
</div>
<h4 class="text-center mt-4">
  <%=@article.title%>
    <%= link_to gravatar_for(@article.user,size: 200),user_path(@article.user)%>
</h4>
<div class="text-center justify-content-center align-items-center fw-semibold badge rounded-pill bg-dark m-1 ">
  <% if @article.categories.any?%>
    <%= render @article.categories%>
      <%end%>
</div>
<div class="container-fluid">
  <div class="card text-center shadow-lg bg-body rounded">
    <div class="card-header fst-italic">
      Featured On rail by <%=@article.user.username%>
    </div>
    <div class="card-body">
      <p class="card-text">
        <%= simple_format(@article.description) %>
      </p>
      <div class="d-flex justify-content-center gap-3">
        <% if logged_in? && (@article.user==current_user || current_user.admin?)%>
          <%= link_to 'Edit' , edit_article_path(@article) ,class:'btn btn-primary'%>
            <%= button_to'Delete' ,article_path(@article),class:'btn btn-danger' , method: :delete%>
              <%end%>
      </div>
    </div>
    <div class="card-footer text-muted">
      Posted <%= time_ago_in_words(@article.created_at)%>
    </div>

  </div>
</div>