config/routes.rb
Rails.application.routes.draw do
  resources :articles
  resources :cars
  root 'pages#home'
  get   'about', to: 'pages#about'
  get   'signup', to: 'users#new'
  get    'login', to: 'sessions#new'
  post   'login', to: 'sessions#create'
  delete   'logout', to: "sessions#destroy"
  resources :users , except:[:new]
  resources :categories, except: [:destroy]
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true ,length: {minimum:3, maximum:25}
  validates_uniqueness_of :name 
    has_many :article_categories
    has_many :articles , through: :article_categories
end 

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin,except: [:index,:show]
    def index
    @categories=Category.all
    end

     def new
       @category=Category.new
     end

    def create
      @category=Category.new(category_params)
      if @category.save
        flash[:notice]="hurrah"
        redirect_to @category
      else
        render "new"
      end
    end

    def show
      @category=Category.find(params[:id])  
      @categories_article=@category.articles
    end
    def edit
      @category=Category.find(params[:id])  
    end
    def update
      @category=Category.find(params[:id])
        if @category.update(category_params)
          flash[:success] = "Object was successfully updated"
          redirect_to @category
        else
          flash[:error] = "Something went wrong"
          render 'edit'
        end
    end
    
    private
    def category_params
        params.require(:category).permit(:name)
    end
    def require_admin
    if !(logged_in? && current_user.admin?)
      flash[:alert]="olny admn can do that"
      redirect_to categories_path
    end
    end
end

app/views/categories/_category.html.erb
<%= category.name%>

app/views/categories/_form.html.erb
<%= form_with(model: @category, data: { turbo: "false" }) do |f| %>
    <div class="mb-3 ">
        <%= f.label :name,"Category Name" ,class:"form-label"%><br />
            <%= f.text_field :name ,class:"form-control",placeholder:"enter name....." %>
    </div>


    <div class="mb-3">
        <%= f.submit class:"btn btn-outline-success"%>
    </div>
    <%end%>

app/views/categories/edit.html.erb
<div class="container">
    <div class="row align-content-center text-center">
        <div class="col-12">
            <h1 class="lead">Edit Category</h1>
            <%= render 'shared/errors' , obj: @category%>

                <%= render 'form' %>

        </div>
    </div>
</div>

app/views/categories/index.html.erb
<h4 class="text-center mt-4">Blogs</h4>


<div class="container-fluid">
    <% @categories.each do |category|%>

        <div class="card text-center shadow-lg bg-body rounded mb-2">

            <div class="card-body">
                <h5 class="card-title">
                    <%= link_to category.name ,category_path(category) ,class:'text-success no-underline'%>
                </h5>
                <p class="card-text">
                    <%= pluralize(category.articles.count,"article")%>
                </p>

                <div class="card-footer text-muted">
                    Posted <%= time_ago_in_words(category.created_at)%> and updated at about <%=
                            time_ago_in_words(category.updated_at)%>
                </div>
            </div>
        </div>

        <%end%>

</div>

app/views/categories/new.html.erb
<div class="container">
    <div class="row align-content-center text-center">
        <div class="col-12">
            <h1 class="lead">create new Category</h1>
            <%= render 'shared/errors' , obj: @category%>
                <%= form_with(model: @category, data: { turbo: "false" }) do |f| %>
                    <div class="mb-3 ">
                        <%= f.label :name,"Category Name" ,class:"form-label"%><br />
                            <%= f.text_field :name ,class:"form-control",placeholder:"enter name....." %>
                    </div>
                  
                   
                    <div class="mb-3">
                        <%= f.submit class:"btn btn-outline-success"%>
                    </div>
                    <%end%>


        </div>
    </div>
</div>

app/views/categories/show.html.erb
<h1>
    <%= @category.name %>
</h1>
<div class="text-center mt-4">
    <% if logged_in? && current_user.admin?%>
        <%=link_to "Edit category" , edit_category_path(@category),class:"btn btn-outline-success"%>
            <%end%>
</div>
<h3 class="text-center mt-4">
    Blogs
</h3>

<%= render 'articles/article' , obj: @categories_article %>