config/routes.rb
Rails.application.routes.draw do
  resources :articles
  resources :cars
  root 'pages#home'
  get   'about', to: 'pages#about'
  get   'signup', to: 'users#new'
  get    'login', to: 'sessions#new'
  post   'login', to: 'sessions#create'
  delete   'logout', to: "sessions#destroy"
  resources :users , except:[:new]
  resources :categories, except: [:destroy]
end

app/views/layouts/_messages.html.erb
<% flash.each do |key,msg|%>
  <div class=" alert alert-<%= key == " notice" ? "success" : "danger" %> text-center" role="alert">
    <%= msg %>
  </div>



  <%end%>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">

    <%= link_to "Onrails" ,root_path , class:"navbar-brand" , id:'logo'%>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">

            <%= link_to "Bloggers" , users_path , class:"nav-link active"%>
          </li>
          <li class="nav-item">
            <%= link_to "Articles" , articles_path , class:"nav-link"%>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Articles
            </a>
            <ul class="dropdown-menu">
              <% if logged_in? %>
                <%= link_to "New Blog" , new_article_path , class:"dropdown-item"%>
                  <%end%>
                    <%= link_to "View Blogs" , articles_path , class:"dropdown-item"%>
                      <%= link_to "Articles" , articles_path , class:"dropdown-item"%>
                        <li>
                          <hr class="dropdown-divider">
                        </li>

            </ul>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Categories
            </a>
            <ul class="dropdown-menu">
              <% if logged_in? && current_user.admin? %>
                <%= link_to "Create new Category" , new_category_path , class:"dropdown-item"%>
                  <%end%>
                    <%= link_to "View Categories" , categories_path , class:"dropdown-item"%>


            </ul>
          </li>
        </ul>
        <!-- user profile -->

        <% if logged_in? %>
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                aria-expanded="false">
                <%= "(Admin)" if current_user.admin? %> r Profile [<%= current_user.username%>]
              </a>
              <ul class=" dropdown-menu">
                <% if logged_in? %>
                  <%= link_to "view Profile" , user_path(current_user), class:"dropdown-item"%>
                    <%end%>
                      <%= link_to "Edit Profile" , edit_user_path(current_user) , class:"dropdown-item"%>

                        <%= button_to "[ Delete Profile ]" , user_path(current_user) , method: :delete,class:"btn
                          btn-outline-danger"%>
              </ul>
            </li>
          </ul>

          <div class="d-flex">


            <%= button_to "Logout" , logout_path , method: :delete,class:"btn btn-outline-success"%>

          </div>
          <%else%>

            <div class="d-flex">


              <%= link_to "Login" , login_path ,class:"btn btn-outline-success p-3"%>
                <%= link_to "SignUp" , signup_path ,class:"btn btn-outline-primary p-3 ml-1"%>
            </div>
            <%end%>

      </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Onrail</title>
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application" , "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application" , "data-turbo-track": "reload" , defer: true %>
  </head>
  <body>
    <%= render 'layouts/nav' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>